services:

  ## database server name : db
  db:
    image: mariadb
    restart: always
    environment: 
      MARIADB_ROOT_PASSWORD: example
  ## username : root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080